### ISSUE TITLE
strip whitespace from key?

### ISSUE THREAD

**Issue by rolanyang** [bramley/phplist-plugin-mailgun#1]
Just pulled my hair out the past 3 hours debugging what turned out to be a stupid error (on my part).
When copying + pasting the mailgun key, I included a whitespace at the beginning.
The mails obviously failed to send but the exception errors didn't make it to the output.

This is definitely a user error, but if it happened to me it might happen to a lot of other people.
Perhaps adding a trim() in there might save some people the same frustration?

        if ($client === null) {
            $client = \Mailgun\Mailgun::create(trim(getConfig('mailgun_api_key')));
            $domain = getConfig('mailgun_domain');

**Comment by bramley** [comment]
It might be better to change core phplist to trim() values when they are entered. It is in file admin/configure.php around line 85

                if (empty($value) && !$info['allowempty']) {
                    //    Error($info['description']. ' ' . $GLOBALS['I18N']->get('cannot be empty'));
                    $haserror = $info['description'].' '.$GLOBALS['I18N']->get('cannot be empty');
                } else {
                    $haserror = SaveConfig($id, $value);
                }

But the plugin should really have handled errors when sending so I will fix that.
![image](https://user-images.githubusercontent.com/3147688/41193962-343940ae-6c0c-11e8-82a7-ec8744a04c4f.png)

**Comment by rolanyang** [comment]
Yep. Considered it might be better to clean the data before saving it, but then wondered if any configs might intentionally need whitespace heading or trailing the input.
