### ISSUE TITLE
Allow EU region to be used

### ISSUE THREAD

**Issue by bramley** [bramley/phplist-plugin-mailgun#2]
@fivefilters I have added the ability to specify the mailgun base URL so that the EU region can be used. If you are able to test this out you can install the new version through the phplist Manage Plugins page using the package URL 

`https://github.com/bramley/phplist-plugin-mailgun/archive/update_libraries.zip`

**Comment by fivefilters** [comment]
Thank you. When I get a bit more time I will test out with your updated plugin and will report back. The simple endpoint URL change I made in the fork did work for me, so I'm sure this will too.

**Comment by bramley** [comment]
I have now merged the update_libraries branch into the master branch.

**Comment by anvaruk** [comment]
doesn't work for me
I had to manually change  api.mailgun.net  -->  api.eu.mailgun.net
in
.../plugins/Mailgun/vendor/mailgun/mailgun-php/src/Mailgun/Mailgun.php

version 1.1.0+20200216
Installed  2020-02-28

**Comment by bramley** [comment]
@anvaruk did you enter the EU endpoint on the Settings page?

**Comment by anvaruk** [comment]
@bramley yes I did
![image](https://user-images.githubusercontent.com/2795267/75630595-1d45b480-5be4-11ea-8ee5-ab8de018521e.png)

I was in contact with mailgun support assuming my domain is not activated, but they suggested that something is not right about EU region, so I tried  the following on Settings page which did not help:
https://api.eu.mailgun.net/v3/mydomain.com/messages
https://api.eu.mailgun.net/v3/mydomain.com
https://api.eu.mailgun.net/v3
https://api.eu.mailgun.net
api.eu.mailgun.net

**Comment by bramley** [comment]
@anvaruk Please can you try this code change to file plugins/Mailgun.php. The value on the Settings page should be `https://api.eu.mailgun.net`

```
        try {
            $result = $client->sendMessage($domain, $parameters, $files);
        } catch (Exception $e) {
```
to

```
        try {
            $result = $client->messages()->send($domain, $parameters, $files);
            return true;
        } catch (Exception $e) {

```

**Comment by anvaruk** [comment]
@bramley it works now )
for both https://api.eu.mailgun.net and  https://api.eu.mailgun.net/v3 (as per mailgun instructions https://documentation.mailgun.com/en/latest/api-intro.html#base-url)

thank you

**Comment by bramley** [comment]
@anvaruk Thanks. I had not fully understood the example in the mailgun documentation. I will include these changes into a proper release.
The 'v3' part is not needed in the base url because it is added by the mailgun code

        $response = $this->httpPostRaw(sprintf('/v3/%s/messages.mime', $domain), $postDataMultipart);
